name: Deploy Portfolio Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install sshpass

    - name: Deploy to VPS
      run: sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o root@diegoaguilar.me 'cd /var/www/html/portfolioWebsite && git fetch && git pull && cd portfolio && npm run build && sudo systemctl restart apache2'
